/**
 * Centralized Arabic content layer (docs/06 §11, docs/19).
 * Modern Standard Arabic for Saudi Arabian business audiences.
 * Keys mirror en.ts exactly.
 */

import type { ContentDictionary } from "@/lib/content/en";

export const ar = {
  "common.brand.short": "FoundEarly",
  "common.brand.full": "FoundEarly Labs",
  "common.product": "معرض القدرات التفاعلي",
  "common.companyContext": "البراق هورايزون للمقاولات",
  "common.action.close": "إغلاق",
  "common.action.cancel": "إلغاء",
  "common.action.confirm": "تأكيد",
  "common.action.open": "فتح",
  "common.loading": "جارٍ التحميل",
  "common.skipToContent": "تخطي إلى المحتوى الرئيسي",
  "common.search": "بحث",
  "common.comingSoon": "قريباً",
  "common.preview": "معاينة",
  "nav.group.workspaces": "مساحات العمل",
  "nav.group.utility": "أدوات مساعدة",
  "nav.utility.about": "حول هذا العرض",
  "nav.workspaceSwitcher": "تبديل مساحة العمل",
  "nav.sectionNav": "أقسام مساحة العمل",
  "nav.projectSelector": "المشروع النشط",
  "nav.breadcrumb": "مسار التنقل",
  "nav.openCommand": "فتح لوحة الأوامر",
  "nav.openSearch": "فتح البحث",
  "nav.openNotifications": "فتح الإشعارات",
  "workspace.projectCommand.label": "قيادة المشاريع",
  "workspace.projectCommand.description": "صحة المحفظة وتفاصيل المشاريع ومعاينات التشغيل.",
  "workspace.projectCommand.section.overview": "نظرة عامة",
  "workspace.projectCommand.section.projectDetail": "تفاصيل المشروع",
  "workspace.projectCommand.section.rfis": "طلبات المعلومات",
  "workspace.projectCommand.section.documents": "المستندات",
  "workspace.projectCommand.section.team": "الفريق",
  "workspace.corporateWebsite.label": "الموقع الإلكتروني للشركة",
  "workspace.corporateWebsite.description": "العرض 01 — موقع شركة احترافي لشركة البراق هورايزون للمقاولات.",
  "workspace.corporateWebsite.section.home": "الرئيسية",
  "workspace.corporateWebsite.section.about": "من نحن",
  "workspace.corporateWebsite.section.services": "الخدمات",
  "workspace.corporateWebsite.section.projects": "المشاريع",
  "workspace.corporateWebsite.section.careers": "الوظائف",
  "workspace.corporateWebsite.section.contact": "تواصل معنا",
  "workspace.contractorOs.label": "ContractorOS",
  "workspace.contractorOs.description": "العرض 02 — منصة إدارة المقاولات لشركة البراق هورايزون للمقاولات.",
  "workspace.contractorOs.section.dashboard": "لوحة التحكم",
  "workspace.contractorOs.section.projects": "المشاريع",
  "workspace.contractorOs.section.workforce": "القوى العاملة",
  "workspace.contractorOs.section.equipment": "المعدات",
  "workspace.contractorOs.section.documents": "المستندات",
  "workspace.contractorOs.section.purchaseOrders": "أوامر الشراء",
  "workspace.contractorOs.section.settings": "الإعدادات",
  "workspace.procurement.label": "المشتريات وجدول الكميات",
  "workspace.procurement.description": "جداول الكميات وسير عمل المشتريات.",
  "workspace.procurement.section.overview": "نظرة عامة",
  "workspace.documentControl.label": "ضبط المستندات",
  "workspace.documentControl.description": "سجل الرسومات والمستندات.",
  "workspace.documentControl.section.overview": "نظرة عامة",
  "workspace.rfiSubmittals.label": "طلبات المعلومات والتقديمات",
  "workspace.rfiSubmittals.description": "دورة طلب المعلومات وسجل التقديمات.",
  "workspace.rfiSubmittals.section.overview": "نظرة عامة",
  "shell.utilityRegion": "منطقة الأدوات",
  "shell.rightUtility": "أدوات سياقية",
  "shell.presentationToggle": "وضع العرض",
  "shell.presentationOn": "وضع العرض مفعّل",
  "shell.presentationOff": "وضع العرض غير مفعّل",
  "shell.themeSwitch": "المظهر",
  "shell.theme.light": "فاتح",
  "shell.theme.dark": "داكن",
  "shell.theme.system": "النظام",
  "shell.languageSwitch": "اللغة",
  "shell.language.en": "الإنجليزية",
  "shell.language.ar": "العربية",
  "shell.language.hint": "تبديل لغة الواجهة بين الإنجليزية والعربية.",
  "empty.workspace.title": "مساحة العمل جاهزة",
  "empty.workspace.description": "هذا القسم مسجّل في محرك مساحات العمل. ستتوفر واجهات المحتوى في مرحلة لاحقة.",
  "empty.search.title": "لا توجد نتائج مطابقة",
  "empty.search.description": "جرّب مصطلحاً مختلفاً، أو امسح الاستعلام لاستعراض الفئات.",
  "empty.notifications.title": "لا توجد إشعارات",
  "empty.notifications.description": "ستظهر إشعارات النظام هنا عند ربط مسار الإشعارات.",
  "empty.presentation.title": "واجهة العرض هادئة",
  "empty.presentation.description": "تم تخفيف الواجهة الثانوية ليبقى التركيز على مساحة العمل. اضغط P للخروج.",
  "empty.noData.title": "لا توجد بيانات في هذا العرض",
  "empty.noData.description":
    "لم تُحمَّل بيانات العرض التوضيحي لهذا السطح بعد. تظل الواجهة قابلة للتنقل بالكامل.",
  "empty.comingSoon.title": "قريباً",
  "empty.comingSoon.description": "هذه المساحة محجوزة في السجل وستُدمج في الواجهة نفسها عند إطلاقها.",
  "command.placeholder": "ابحث في الأوامر والوجهات…",
  "command.empty": "لا توجد أوامر تطابق هذا الاستعلام.",
  "command.recent": "الأخيرة",
  "command.quickActions": "إجراءات سريعة",
  "command.category.navigation": "التنقل",
  "command.category.presentation": "العرض",
  "command.category.simulator": "المحاكي",
  "command.category.workspace": "مساحة العمل",
  "command.category.system": "النظام",
  "command.open": "لوحة الأوامر",
  "search.placeholder": "ابحث في المعرض…",
  "search.recent": "عمليات البحث الأخيرة",
  "search.categories": "الفئات",
  "search.loading": "جارٍ البحث…",
  "search.category.workspaces": "مساحات العمل",
  "search.category.sections": "الأقسام",
  "search.category.commands": "الأوامر",
  "search.category.projects": "المشاريع",
  "search.indexHint": "فهرس مؤقت — لا توجد خلفية بحث مباشرة في هذه المرحلة.",
  "notifications.title": "الإشعارات",
  "notifications.badge": "إشعارات غير مقروءة",
  "notifications.markAllRead": "تعيين الكل كمقروء",
  "notifications.emptyAction": "بنية الإشعارات جاهزة",
  "about.title": "حول هذا العرض",
  "about.description":
    "تم بناء معرض القدرات التفاعلي هذا بواسطة FoundEarly Labs باستخدام بيانات توضيحية لشركة البراق هورايزون للمقاولات. يعرض جودة البنية والتفاعل — وليس نظاماً تشغيلياً حياً.",
  "about.shellReady": "واجهة التطبيق المؤسسية ومحرك مساحات العمل مفعّلان.",
  "notFound.title": "الصفحة غير موجودة",
  "notFound.description": "هذا الرابط ليس جزءاً من المعرض الحالي. عد إلى مساحة قيادة المشاريع.",
  "notFound.action": "فتح قيادة المشاريع",
  "landing.nav.solutions": "الحلول",
  "landing.nav.showcase": "معرض الحلول التفاعلي",
  "landing.hero.brand": "FoundEarly Labs",
  "landing.hero.headline": "حلول ذكاء اصطناعي وبرمجيات مصممة لشركات المقاولات.",
  "landing.hero.support":
    "نبني مواقع إلكترونية مخصصة، وبرمجيات داخلية، وأنظمة ذكاء اصطناعي، وأتمتة أعمال للمقاولين والشركات الهندسية التي تحتاج أدوات تتوافق مع طريقة إدارة مشاريعها فعلياً.",
  "landing.hero.ctaPrimary": "استكشف الحلول",
  "landing.hero.ctaSecondary": "معرض الحلول التفاعلي",
  "landing.trust.customSoftware": "برمجيات مخصصة",
  "landing.trust.aiAutomation": "أتمتة بالذكاء الاصطناعي",
  "landing.trust.dashboards": "لوحات تحكم مؤسسية",
  "landing.trust.workflows": "سير عمل المقاولات",
  "landing.trust.businessAutomation": "أتمتة الأعمال",
  "landing.trust.webPlatforms": "منصات ويب",
  "landing.about.title": "عن FoundEarly Labs",
  "landing.about.body":
    "نشارك شركات المقاولات في تحديث العمليات عبر برمجيات مخصصة. يتشكل عملنا وفق كيفية اعتماد المقاولين وشركات MEP والفرق الهندسية لطلبات المعلومات وضبط المستندات وإدارة المشاريع — لا وفق قوالب SaaS عامة.",
  "landing.audience.title": "من نخدم",
  "landing.audience.support": "فرق تحتاج برمجيات تشغيلية بمستوى جدية العمل الذي تنفذه.",
  "landing.audience.general": "المقاولون العامون",
  "landing.audience.mep": "مقاولو MEP",
  "landing.audience.civil": "مقاولو الأعمال المدنية",
  "landing.audience.industrial": "مقاولو المشاريع الصناعية",
  "landing.audience.engineering": "المستشارون الهندسيون",
  "landing.audience.aramco": "الشركات المعتمدة لدى أرامكو",
  "landing.build.title": "ما نبنيه",
  "landing.build.support": "أنظمة عملية للمكتب والموقع وطاولة القرار التنفيذي.",
  "landing.build.websites.title": "المواقع الإلكترونية للشركات",
  "landing.build.websites.body": "حضور رقمي موثوق يعكس كيف تفوز شركتك بالأعمال فعلياً.",
  "landing.build.websites.cta": "فتح العرض 01",
  "landing.build.contractor.title": "أنظمة إدارة المقاولات",
  "landing.build.contractor.body": "منصات داخلية للمشاريع والفرق والموردين والرقابة اليومية.",
  "landing.build.contractor.cta": "فتح العرض 02",
  "landing.build.ai.title": "مساعدو الذكاء الاصطناعي",
  "landing.build.ai.body": "مساعدون محددون النطاق يستندون إلى مستنداتك وسجلاتك وسياق التشغيل.",
  "landing.build.dashboards.title": "لوحات التحكم التنفيذية",
  "landing.build.dashboards.body": "رؤية للجدول والميزانية والمخاطر مصممة لصنّاع القرار.",
  "landing.build.mobile.title": "تطبيقات الجوال",
  "landing.build.mobile.body": "تطبيقات ميدانية للفحص والتحديثات وتنسيق الموقع.",
  "landing.build.automation.title": "أتمتة الأعمال",
  "landing.build.automation.body": "استبدل تسليمات الجداول الإلكترونية بسير عمل موثوق وقابل للتكرار.",
  "landing.build.documents.title": "إدارة المستندات",
  "landing.build.documents.body": "سجلات مضبوطة للرسومات والتقديمات وسجل الإصدارات.",
  "landing.why.title": "لماذا FoundEarly",
  "landing.why.support": "مبني كشريك هندسي، لا كعرض منتج جاهز.",
  "landing.why.traditional": "البرمجيات التقليدية",
  "landing.why.foundearly": "FoundEarly Labs",
  "landing.why.item1.traditional": "تفرض منتجها على عملياتك",
  "landing.why.item1.ours": "تُبنى حول سير عملك",
  "landing.why.item2.traditional": "وحدات جامدة ودورات تغيير بطيئة",
  "landing.why.item2.ours": "تطوير مخصص قابل للتوسع",
  "landing.why.item3.traditional": "واجهات كثيفة وقديمة",
  "landing.why.item3.ours": "واجهة حديثة ودقيقة",
  "landing.why.item4.traditional": "الذكاء الاصطناعي يُضاف لاحقاً",
  "landing.why.item4.ours": "جاهز للذكاء الاصطناعي من البداية",
  "landing.why.item5.traditional": "جداول تسليم طويلة",
  "landing.why.item5.ours": "تسليم سريع ومركّز",
  "landing.cta.title": "لنبنِ برمجيات حول أعمالك.",
  "landing.cta.support": "افتح معرض القدرات التفاعلي لترى كيف نصمم برمجيات المقاولات المؤسسية.",
  "landing.cta.action": "فتح معرض الحلول التفاعلي",
  "website.nav.label": "موقع الشركة",
  "website.nav.home": "الرئيسية",
  "website.nav.about": "من نحن",
  "website.nav.services": "الخدمات",
  "website.nav.projects": "المشاريع",
  "website.nav.careers": "الوظائف",
  "website.nav.contact": "تواصل معنا",
  "website.nav.contactCta": "تواصل معنا",
  "website.nav.open": "فتح القائمة",
  "website.nav.close": "إغلاق القائمة",
  "website.footer.offices": "المكتب الرئيسي",
  "website.footer.contact": "التواصل",
  "website.footer.demoNote": "العرض التوضيحي 01 — معرض FoundEarly Labs",
  "website.home.hero.title": "تنفيذ مقاولات للعملاء الصناعيين والمدنيين.",
  "website.home.hero.support":
    "تخطط البراق هورايزون للمقاولات وتنفذ حزماً معقدة عبر المنطقة الشرقية والرياض — بالانضباط الذي يتوقعه المالكون الصناعيون.",
  "website.home.hero.ctaPrimary": "عرض المشاريع",
  "website.home.hero.ctaSecondary": "طلب اجتماع",
  "website.home.intro.title": "نبذة عن الشركة",
  "website.home.intro.body":
    "تأسست عام 2009 ومقرها الرئيسي في الخبر، البراق هورايزون مقاول عام من الدرجة الثانية بقدرة تنفيذ ذاتي لأعمال MEP. نخدم العملاء الصناعيين والتجاريين ومشاريع البنية التحتية الذين يحتاجون تقارير واضحة وواجهات مضبوطة وفرقاً ميدانية تعامل السلامة كنظام تسليم.",
  "website.home.services.title": "الخدمات الأساسية",
  "website.home.services.support": "حزم منضبطة من أعمال التمكين حتى MEP والتسليم النهائي.",
  "website.home.services.cta": "جميع الخدمات",
  "website.home.projects.title": "مشاريع مختارة",
  "website.home.projects.support": "عينة من الأعمال الجارية والمكتملة عبر محفظتنا.",
  "website.home.why.title": "لماذا تختارنا",
  "website.home.why.support": "ما يقيّمه العملاء عند اختيار مقاول للأعمال الصناعية.",
  "website.home.clients.title": "عملاء مختارون",
  "website.home.cta.title": "ناقش حزمتك التالية.",
  "website.home.cta.support": "تحدث مع فريقنا في الخبر حول النطاق والجدول ونهج التسليم لمشروعك.",
  "website.home.cta.action": "تواصل مع البراق هورايزون",
  "website.about.eyebrow": "من نحن",
  "website.about.title": "مبنيون للتسليم بمعايير صناعية.",
  "website.about.support":
    "سبعة عشر عاماً من انضباط المقاولات عبر الحزم المدنية والصناعية وMEP في المملكة العربية السعودية.",
  "website.about.story.title": "قصة الشركة",
  "website.about.story.p1":
    "تأسست شركة البراق هورايزون للمقاولات عام 2009 في الخبر لخدمة العملاء الصناعيين والتجاريين الذين يحتاجون مقاولاً يستطيع تنسيق الأعمال المدنية وMEP دون فقدان السيطرة على الجدول.",
  "website.about.story.p2":
    "نوظف اليوم نحو 940 متخصصاً ونعمل عبر الخبر والدمام والجبيل والظهران والرياض وينبع — منفذين منشآت ومرافق وأعمال تمكين وفق متطلبات الدرجة الثانية ومتطلبات أرامكو.",
  "website.about.mission.title": "الرسالة",
  "website.about.mission.body":
    "تسليم حزم المقاولات بجدول متوقع ورقابة تجارية شفافة ودون أي تنازل عن سلامة الموقع.",
  "website.about.vision.title": "الرؤية",
  "website.about.vision.body":
    "أن نكون المقاول الصناعي المفضل في الشريحة المتوسطة بالمنطقة الشرقية — مقاساً بالعملاء المتكررين والتدقيق النظيف والفرق التي تنمو مع كل مشروع.",
  "website.about.leadership.title": "القيادة",
  "website.about.leadership.support":
    "فريق قيادة أساسي يعمل عبر المحفظة — الأسماء نفسها التي يلتقيها العملاء في كل حزمة رئيسية.",
  "website.about.safety.title": "الالتزام بالسلامة",
  "website.about.safety.body":
    "يعمل كل موقع وفق انضباط تصاريح العمل، ولقاءات الأدوات اليومية، وصلاحية إيقاف العمل لأي حالة غير آمنة. تُبلَّغ مؤشرات السلامة بنفس جدية الجدول والتكلفة.",
  "website.about.quality.title": "الالتزام بالجودة",
  "website.about.quality.body":
    "خطط الفحص والاختبار، وسير عمل MIR/WIR، وإغلاق تقارير عدم المطابقة تُدار عبر سجلات جودة المشروع. لا نتعامل مع الجودة كأوراق تُستكمل بعد التنفيذ.",
  "website.about.certs.title": "الشهادات",
  "website.services.eyebrow": "الخدمات",
  "website.services.title": "قدرات تتوافق مع كيفية طرح الحزم فعلياً.",
  "website.services.support": "مدني، صناعي، MEP، بنية تحتية، صيانة، وإدارة مشاريع — منظمة لواجهات واضحة.",
  "website.projects.eyebrow": "المشاريع",
  "website.projects.title": "محفظة عبر الأعمال الصناعية والتجارية وأعمال التمكين.",
  "website.projects.support": "ست حزم تمثيلية من محفظة البراق هورايزون. القيم معروضة بالريال السعودي.",
  "website.projects.meta.location": "الموقع",
  "website.projects.meta.value": "القيمة",
  "website.projects.meta.year": "سنة الإنجاز",
  "website.projects.meta.scope": "نوع النطاق",
  "website.careers.eyebrow": "الوظائف",
  "website.careers.title": "ابنِ مع فريق يأخذ التسليم بجدية.",
  "website.careers.support": "وظائف مفتوحة عبر المشاريع والهندسة والجودة وضبط المستندات.",
  "website.careers.culture.title": "ثقافة الشركة",
  "website.careers.culture.body":
    "نوظف من يتواصلون بوضوح، ويحترمون بروتوكولات الموقع، ويتعاملون مع التوثيق كجزء من العمل — لا كأمر مؤجل. تتناوب الفرق بين التخطيط المكتبي والتنفيذ الميداني مع مشرفين مسؤولين.",
  "website.careers.benefits.title": "المزايا",
  "website.careers.open.title": "الوظائف المتاحة",
  "website.careers.open.support": "الفرص الحالية. الطلبات توضيحية في هذا العرض.",
  "website.careers.apply.title": "قدّم طلبك",
  "website.careers.apply.support":
    "أرسل سيرتك الذاتية وملاحظة موجزة عن خبرتك في المشاريع ذات الصلة إلى بريد الوظائف، أو استخدم نموذج التواصل.",
  "website.careers.apply.cta": "تواصل مع التوظيف",
  "website.contact.eyebrow": "تواصل معنا",
  "website.contact.title": "تحدث مع فريق المكتب الرئيسي.",
  "website.contact.support": "استفسارات المشاريع وتعريف الموردين والوظائف — تُدار من الخبر.",
  "website.contact.office.title": "المكتب",
  "website.contact.details.title": "خطوط مباشرة",
  "website.contact.phone": "الهاتف",
  "website.contact.email": "البريد الإلكتروني",
  "website.contact.map.title": "خريطة توضيحية",
  "website.contact.map.support": "موقع المكتب الرئيسي في الخبر. تضمين خريطة مباشرة غير مطلوب لهذا العرض.",
  "website.contact.form.title": "أرسل رسالة",
  "website.contact.form.support": "نموذج واجهة فقط — لا يوجد إرسال خلفي في هذا العرض.",
  "website.contact.form.name": "الاسم الكامل",
  "website.contact.form.email": "البريد المهني",
  "website.contact.form.company": "الشركة",
  "website.contact.form.message": "الرسالة",
  "website.contact.form.submit": "إرسال الرسالة",
  "website.contact.form.note": "للتوضيح فقط — لا يُرسل أي شيء.",
  "website.contact.form.success": "سُجّلت الرسالة محلياً لهذه الجلسة التوضيحية.",
  "os.dashboard.eyebrow": "ContractorOS",
  "os.dashboard.title": "لوحة التحكم التنفيذية",
  "os.dashboard.support":
    "صحة المحفظة لشركة البراق هورايزون للمقاولات — الجدول والقوى العاملة والمعدات والرقابة التجارية.",
  "os.dashboard.projectStatus": "حالة المشاريع",
  "os.dashboard.viewProjects": "عرض المشاريع",
  "os.dashboard.activity": "النشاط الأخير",
  "os.dashboard.deadlines": "المواعيد القادمة",
  "os.dashboard.quickActions": "إجراءات سريعة",
  "os.kpi.activeProjects": "المشاريع النشطة",
  "os.kpi.activeProjects.hint": "باستثناء الحزم المكتملة",
  "os.kpi.employeesOnSite": "الموظفون في الموقع",
  "os.kpi.employeesOnSite.hint": "عبر المنطقة الشرقية والرياض",
  "os.kpi.equipmentUtilization": "استخدام المعدات",
  "os.kpi.equipmentUtilization.hint": "الأصول المخصصة مقابل الأسطول",
  "os.kpi.openPos": "أوامر الشراء المفتوحة",
  "os.kpi.openPos.hint": "لم تُسلَّم بعد",
  "os.kpi.pendingApprovals": "الاعتمادات المعلقة",
  "os.kpi.pendingApprovals.hint": "أوامر شراء بانتظار توقيع المدير",
  "os.kpi.monthlyRevenue": "الإيراد الشهري",
  "os.kpi.monthlyRevenue.hint": "التقدم المعترف به هذا الشهر",
  "os.action.projects": "فتح المشاريع",
  "os.action.workforce": "سجل القوى العاملة",
  "os.action.equipment": "أسطول المعدات",
  "os.action.documents": "مستعرض المستندات",
  "os.action.pos": "أوامر الشراء",
  "os.action.reviewApprovals": "مراجعة الاعتمادات",
  "os.projects.title": "المشاريع",
  "os.projects.support": "ست حزم في محفظة البراق هورايزون. اختر صفاً لعرض نظرة عامة واضحة.",
  "os.projects.search": "ابحث في المشاريع…",
  "os.projects.back": "العودة إلى المشاريع",
  "os.projects.meta.location": "الموقع",
  "os.projects.meta.value": "قيمة المشروع",
  "os.projects.meta.manager": "مدير المشروع",
  "os.projects.meta.client": "العميل",
  "os.projects.meta.type": "النوع",
  "os.projects.meta.completion": "تاريخ الإنجاز",
  "os.workforce.title": "القوى العاملة",
  "os.workforce.support": "السجل الأساسي في المواقع النشطة. صور رمزية بالأحرف الأولى — دون صور وهمية.",
  "os.workforce.search": "ابحث في الموظفين…",
  "os.workforce.col.employee": "الموظف",
  "os.workforce.col.role": "الدور",
  "os.workforce.col.site": "الموقع",
  "os.workforce.col.status": "الحالة",
  "os.workforce.col.shift": "الوردية",
  "os.workforce.col.project": "المشروع",
  "os.equipment.title": "المعدات",
  "os.equipment.support": "معدات مملوكة وفي الساحة مخصصة عبر المحفظة.",
  "os.equipment.search": "ابحث في المعدات…",
  "os.equipment.col.asset": "الأصل",
  "os.equipment.col.type": "النوع",
  "os.equipment.col.status": "الحالة",
  "os.equipment.col.location": "الموقع",
  "os.equipment.col.project": "المشروع المخصص",
  "os.equipment.col.maintenance": "الصيانة القادمة",
  "os.documents.title": "المستندات",
  "os.documents.support":
    "مجلدات مضبوطة للعقود وطلبات المعلومات وجداول الكميات والرسومات والفواتير وأدلة السلامة.",
  "os.documents.search": "ابحث في المستندات…",
  "os.documents.folder": "الفئة",
  "os.documents.folders": "المجلدات",
  "os.documents.recent": "المستندات",
  "os.documents.preview": "معاينة",
  "os.documents.previewHint": "معاينة مستند توضيحية — للعرض فقط.",
  "os.documents.none": "لم يُحدد مستند.",
  "os.documents.meta.id": "معرف المستند",
  "os.documents.meta.owner": "المالك",
  "os.documents.meta.project": "المشروع",
  "os.documents.meta.status": "الحالة",
  "os.pos.title": "أوامر الشراء",
  "os.pos.support": "سجل أوامر شراء للقراءة فقط لموردي البراق هورايزون. لا يوجد تحرير في هذا العرض.",
  "os.pos.search": "ابحث في أوامر الشراء…",
  "os.pos.col.number": "رقم أمر الشراء",
  "os.pos.col.vendor": "المورد",
  "os.pos.col.amount": "المبلغ",
  "os.pos.col.status": "الحالة",
  "os.pos.col.approval": "الاعتماد",
  "os.pos.col.project": "المشروع",
  "os.settings.title": "الإعدادات",
  "os.settings.support": "تفضيلات الشركة لعرض ContractorOS. واجهة فقط — لا يُحفظ شيء.",
  "os.settings.nav": "أقسام الإعدادات",
  "os.settings.nav.branding": "الهوية",
  "os.settings.nav.notifications": "الإشعارات",
  "os.settings.nav.language": "اللغة",
  "os.settings.nav.theme": "المظهر",
  "os.settings.nav.roles": "الأدوار",
  "os.settings.nav.permissions": "الصلاحيات",
  "os.settings.branding.support": "العلامة التجارية وهوية الشركة المعروضة عبر المنصة.",
  "os.settings.branding.company": "الاسم القانوني",
  "os.settings.branding.short": "الاسم المختصر",
  "os.settings.branding.mark": "الرمز",
  "os.settings.branding.accent": "رمز اللون المميز",
  "os.settings.notifications.support": "تفضيلات إشعارات توضيحية للعمليات الحية.",
  "os.settings.notifications.approvals": "تنبيهات اعتماد أوامر الشراء",
  "os.settings.notifications.rfis": "تنبيهات اتفاقية مستوى الخدمة لطلبات المعلومات",
  "os.settings.notifications.maintenance": "تذكيرات صيانة المعدات",
  "os.settings.notifications.weekly": "ملخص المحفظة الأسبوعي",
  "os.settings.language.support": "لغة الواجهة وتنسيق التاريخ للعرض.",
  "os.settings.language.ui": "لغة الواجهة",
  "os.settings.language.dates": "تنسيق التاريخ",
  "os.settings.theme.support": "تفضيلات المظهر للعرض والاستخدام اليومي.",
  "os.settings.theme.mode": "وضع الألوان",
  "os.settings.theme.density": "الكثافة",
  "os.settings.roles.support": "تعريفات الأدوار المستمدة من هيكل تسليم البراق هورايزون.",
  "os.settings.roles.illustrative": "توضيحي",
  "os.settings.permissions.support": "مفاتيح قدرات لأدوار العرض — غير مُنفَّذة.",
  "os.settings.permissions.export": "تصدير السجلات",
  "os.settings.permissions.approvePo": "اعتماد أوامر الشراء",
  "os.settings.permissions.editDocs": "تحرير المستندات المضبوطة",
  "os.settings.permissions.manageUsers": "إدارة حسابات المستخدمين",
  "os.settings.save": "حفظ الإعدادات",
  "os.settings.reset": "تجاهل",
  "os.settings.saved": "سُجّلت الإعدادات محلياً لهذه الجلسة التوضيحية.",
  "os.settings.note": "واجهة فقط — دون حفظ خلفي.",
  "os.filter.status": "الحالة",
  "os.filter.all": "الكل",
  "os.empty.filtered": "لا توجد سجلات تطابق هذه عوامل التصفية. امسح البحث أو الحالة.",
  "shell.language.badge.en": "EN",
  "shell.language.badge.ar": "ع",
  "common.progress": "التقدم",
  "error.boundary.title": "حدث انقطاع في هذا العرض",
  "error.boundary.description": "استعاد المعرض حالته بأمان. أعد المحاولة في هذا السطح، أو تابع من تنقل الواجهة.",
  "error.boundary.retry": "إعادة المحاولة",
  "overlay.close": "إغلاق الطبقة",
  "landing.nav.aria": "الصفحة الرئيسية",
  "landing.capabilities.aria": "القدرات",
  "command.setActiveProject": "تعيين المشروع النشط {code}",
  "search.project.defaultDescription": "المشروع النشط الافتراضي بعد إعادة ضبط العرض",
  "shortcut.presentation": "تبديل وضع العرض",
  "shortcut.fullscreen": "تبديل ملء الشاشة",
  "status.onTrack": "وفق الجدول",
  "status.atRisk": "معرّض للخطر",
  "status.delayed": "متأخر",
  "status.complete": "مكتمل",
  "status.draft": "مسودة",
  "status.pendingApproval": "بانتظار الاعتماد",
  "status.approved": "معتمد",
  "status.issuedToVendor": "صادر للمورد",
  "status.delivered": "تم التسليم",
  "status.onHold": "موقوف",
  "status.current": "ساري",
  "status.superseded": "منسوخ",
  "status.underRevision": "قيد المراجعة",
  "status.onSite": "في الموقع",
  "status.offShift": "خارج الوردية",
  "status.leave": "إجازة",
  "status.assigned": "مخصص",
  "status.available": "متاح",
  "status.maintenance": "صيانة",
  "status.day": "نهاري",
  "status.night": "ليلي",
  "status.office": "مكتبي",
  "status.fullTime": "دوام كامل",
  "status.contract": "تعاقد",
  "status.watch": "قيد المتابعة",
  "status.overdue": "متأخر عن الموعد",
  "status.open": "مفتوح",
  "os.settings.language.option.en": "الإنجليزية",
  "os.settings.language.option.ar": "العربية",
  "os.settings.language.dateFormat": "DD MMM YYYY",
  "os.settings.theme.option.system": "النظام",
  "os.settings.theme.option.light": "فاتح",
  "os.settings.theme.option.dark": "داكن",
  "os.settings.theme.option.comfortable": "مريح",
  "os.settings.theme.option.compact": "مضغوط",
  "os.settings.branding.accentValue": "اللون الأساسي للعلامة",
  "os.settings.roles.projectDirector": "مدير المشاريع",
  "os.settings.roles.projectDirector.access": "المحفظة كاملة",
  "os.settings.roles.projectManager": "مدير المشروع",
  "os.settings.roles.projectManager.access": "المشاريع المخصصة",
  "os.settings.roles.procurementLead": "مسؤول المشتريات",
  "os.settings.roles.procurementLead.access": "أوامر الشراء والموردون",
  "os.settings.roles.documentController": "ضابط المستندات",
  "os.settings.roles.documentController.access": "السجلات والرسومات",
  "website.company.tagline": "مقاولات صناعية ومدنية عبر المملكة.",
  "website.company.industry": "مقاول عام",
  "website.company.headquarters": "الخبر، المنطقة الشرقية، المملكة العربية السعودية",
  "website.company.classification": "مقاول من الدرجة الثانية — الهيئة السعودية للمقاولين",
  "website.company.stat.years": "سنوات في السوق",
  "website.company.stat.projects": "مشاريع مُنجزة",
  "website.company.stat.professionals": "متخصصون",
  "website.company.stat.cities": "مدن نخدمها",
  "website.company.cert.iso9001": "ISO 9001:2015 إدارة الجودة",
  "website.company.cert.iso45001": "ISO 45001:2018 الصحة والسلامة المهنية",
  "website.company.cert.iso14001": "ISO 14001:2015 الإدارة البيئية",
  "website.company.cert.aramco": "مورد معتمد لدى أرامكو (AR-CL-2291)",
  "website.company.cert.grade2": "الهيئة السعودية للمقاولين — الدرجة الثانية",
  "website.company.city.khobar": "الخبر",
  "website.company.city.dammam": "الدمام",
  "website.company.city.jubail": "مدينة الجبيل الصناعية",
  "website.company.city.dhahran": "الظهران",
  "website.company.city.riyadh": "الرياض",
  "website.company.city.yanbu": "ينبع",
  "website.company.address.street": "طريق الأمير فيصل بن فهد",
  "website.company.address.city": "الخبر 34427",
  "website.company.address.country": "المملكة العربية السعودية",
  "website.service.civil.title": "الإنشاءات المدنية",
  "website.service.civil.summary": "خرسانة إنشائية وأعمال ترابية وأغلفة مبانٍ للمنشآت الصناعية والتجارية.",
  "website.service.industrial.title": "المشاريع الصناعية",
  "website.service.industrial.summary": "منشآت دعم العمليات وترقيات المرافق وبنية المصانع لمواقع البتروكيماويات والتصنيع.",
  "website.service.mep.title": "MEP",
  "website.service.mep.summary": "حزم ميكانيكية وكهربائية وصحية تُنفَّذ بإشراف داخلي ومقاولين من الباطن مؤهلين.",
  "website.service.infrastructure.title": "البنية التحتية",
  "website.service.infrastructure.summary":
    "طرق ومرافق وأعمال تمكين وتطوير مواقع لمشاريع الخدمات اللوجستية والاستخدام المختلط.",
  "website.service.maintenance.title": "الصيانة",
  "website.service.maintenance.summary":
    "دعم الإيقاف المخطط والأعمال التصحيحية وصيانة المرافق وفق بيانات طريقة عمل مضبوطة.",
  "website.service.pm.title": "إدارة المشاريع",
  "website.service.pm.summary":
    "ضبط الجدول وتقارير التكلفة وضبط المستندات وواجهة العميل عبر الحزم متعددة التخصصات.",
  "website.why.delivery.title": "انضباط التسليم",
  "website.why.delivery.body": "يُعامل ضبط الجدول والتكلفة والمستندات كأنظمة مشروع أساسية — لا كأمور مؤجلة.",
  "website.why.industrial.title": "مصداقية صناعية",
  "website.why.industrial.body":
    "عمليات متوافقة مع أرامكو وتصنيف من الدرجة الثانية للعملاء الذين يتطلبون قدرة مورد مثبتة.",
  "website.why.mep.title": "قوة التنفيذ الذاتي لـ MEP",
  "website.why.mep.body": "تُخطَّط حزم MEP وتُشرف داخلياً، مما يقلل مخاطر الواجهات في المنشآت المعقدة.",
  "website.why.safety.title": "السلامة قبل الجدول",
  "website.why.safety.body":
    "انضباط تصاريح العمل ولقاءات الأدوات وصلاحية إيقاف العمل غير قابلة للتفاوض في كل موقع.",
  "website.benefit.1": "راتب تنافسي ومراجعة أداء سنوية",
  "website.benefit.2": "تغطية طبية للموظفين والمعالين المؤهلين",
  "website.benefit.3": "مسارات مهنية منظمة عبر المشاريع والتخصصات",
  "website.benefit.4": "تناوب بين الموقع والمكتب بمعايير واضحة للصحة والسلامة والبيئة",
  "website.benefit.5": "دعم تدريب للشهادات الفنية والمهنية",
  "fixture.type.industrial": "صناعي",
  "fixture.type.industrialCivil": "صناعي / مدني",
  "fixture.type.commercialMep": "تجاري / MEP",
  "fixture.type.industrialMep": "صناعي / MEP",
  "fixture.type.civil": "مدني",
  "fixture.location.jubail": "مدينة الجبيل الصناعية",
  "fixture.location.dhahran": "الظهران",
  "fixture.location.riyadh": "الرياض",
  "fixture.location.yanbu": "ينبع",
  "fixture.location.khobar": "الخبر",
  "fixture.location.dammam": "الدمام",
  "fixture.location.khobarHq": "الخبر (المقر)",
  "fixture.location.khobarYard": "ساحة الخبر",
  "fixture.location.jubailShort": "الجبيل",
  "fixture.project.P-1042.name": "تحديث مرافق العمليات في الجبيل",
  "fixture.project.P-1042.scope": "ممر مرافق ورفوف أنابيب وحزم مدنية لبنية دعم العمليات.",
  "fixture.project.P-1042.summary": "ممر مرافق ورفوف أنابيب وحزم مدنية لبنية دعم العمليات.",
  "fixture.project.P-1058.name": "توسعة مركز الظهران اللوجستي",
  "fixture.project.P-1058.scope": "توسعة مستودع ورصف ساحة وبنية تصريف لمشغّل لوجستي إقليمي.",
  "fixture.project.P-1058.summary": "توسعة مستودع ورصف ساحة وبنية تصريف.",
  "fixture.project.P-1071.name": "الحرم المؤسسي في الرياض — المرحلة 2",
  "fixture.project.P-1071.scope": "هيكل تجاري وواجهة وتشطيب MEP لحرم مؤسسي متعدد المباني.",
  "fixture.project.P-1071.summary": "هيكل تجاري وواجهة وتشطيب MEP لحرم متعدد المباني.",
  "fixture.project.P-1083.name": "منشأة دعم تحلية المياه في ينبع",
  "fixture.project.P-1083.scope": "مبانٍ داعمة بقيادة MEP وغرف كهربائية وأعمال مدنية مساندة لحرم تحلية.",
  "fixture.project.P-1083.summary": "مبانٍ داعمة بقيادة MEP وغرف كهربائية وأعمال مدنية مساندة.",
  "fixture.project.P-1096.name": "واجهة الخبر البحرية متعددة الاستخدامات — أعمال التمكين",
  "fixture.project.P-1096.nameShort": "واجهة الخبر البحرية — أعمال التمكين",
  "fixture.project.P-1096.scope": "تمكين الموقع وهياكل احتجاز ومرافق لتطوير ساحلي متعدد الاستخدامات.",
  "fixture.project.P-1096.summary": "تمكين الموقع وهياكل احتجاز ومرافق لاستخدام مختلط ساحلي.",
  "fixture.project.P-1102.name": "مجمع المستودعات الصناعية في الجبيل",
  "fixture.project.P-1102.scope": "أربع صالات مستودعات وكتلة مكاتب وأعمال خارجية لمشغّل مناطق صناعية.",
  "fixture.project.P-1102.summary": "أربع صالات مستودعات وكتلة مكاتب وأعمال خارجية.",
  "fixture.leader.faisal.role": "مدير المشاريع",
  "fixture.leader.faisal.focus": "تسليم المحفظة وحوكمة العملاء عبر الحزم الصناعية في المنطقة الشرقية.",
  "fixture.leader.noura.role": "مدير مشاريع أول",
  "fixture.leader.noura.focus": "ضبط الجدول والرقابة التجارية للمشاريع الصناعية والمدنية متعددة التخصصات.",
  "fixture.leader.lina.role": "مدير ضمان ومراقبة الجودة",
  "fixture.leader.lina.focus": "أنظمة الفحص وإغلاق تقارير عدم المطابقة وأنظمة الجودة المتوافقة مع ISO.",
  "fixture.leader.khalid.role": "مسؤول المشتريات",
  "fixture.leader.khalid.focus":
    "تأهيل الموردين والمواد ذات مدد التوريد الطويلة وسلاسل التوريد المتوافقة مع أرامكو.",
  "fixture.role.pmRiyadh.title": "مدير مشروع — تجاري",
  "fixture.role.pmRiyadh.department": "المشاريع",
  "fixture.role.pmRiyadh.summary":
    "قيادة تسليم حزم الحرم والمشاريع التجارية، بما في ذلك تقارير العميل وضبط أوامر التغيير.",
  "fixture.role.peJubail.title": "مهندس مشروع — مدني",
  "fixture.role.peJubail.department": "الهندسة",
  "fixture.role.peJubail.summary":
    "دعم التنفيذ الميداني وطلبات المعلومات وبيانات طريقة العمل في الحزم المدنية الصناعية.",
  "fixture.role.qaDammam.title": "مهندس ضمان ومراقبة الجودة",
  "fixture.role.qaDammam.department": "الجودة",
  "fixture.role.qaDammam.summary": "تخطيط الفحوصات وإدارة سير عمل MIR/WIR والحفاظ على سجل جودة المشروع.",
  "fixture.role.dcKhobar.title": "ضابط مستندات",
  "fixture.role.dcKhobar.department": "ضبط المستندات",
  "fixture.role.dcKhobar.summary": "الحفاظ على سجلات الرسومات والتقديمات بضبط مراجعات منضبط.",
  "fixture.job.projectDirector": "مدير المشاريع",
  "fixture.job.seniorProjectManager": "مدير مشاريع أول",
  "fixture.job.projectManager": "مدير المشروع",
  "fixture.job.projectEngineerCivil": "مهندس مشروع (مدني)",
  "fixture.job.projectEngineerMep": "مهندس مشروع (MEP)",
  "fixture.job.qaqcManager": "مدير ضمان ومراقبة الجودة",
  "fixture.job.procurementLead": "مسؤول المشتريات",
  "fixture.job.documentController": "ضابط المستندات",
  "fixture.job.siteEngineer": "مهندس موقع",
  "fixture.job.costController": "مراقب التكاليف",
  "fixture.equipment.type.excavator": "حفّارة",
  "fixture.equipment.type.crane": "رافعة",
  "fixture.equipment.type.concretePump": "مضخة خرسانة",
  "fixture.equipment.type.generator": "مولّد",
  "fixture.equipment.type.forklift": "رافعة شوكية",
  "fixture.equipment.EX-1.name": "حفّارة EX-1",
  "fixture.equipment.EX-2.name": "حفّارة EX-2",
  "fixture.equipment.TC-1.name": "رافعة برجية TC-1",
  "fixture.equipment.MC-1.name": "رافعة متحركة MC-1 (50 طن)",
  "fixture.equipment.CP-1.name": "مضخة خرسانة CP-1",
  "fixture.equipment.GS-1.name": "مجموعة مولّد GS-1 (500 ك.ف.أ)",
  "fixture.equipment.GS-2.name": "مجموعة مولّد GS-2 (500 ك.ف.أ)",
  "fixture.equipment.FL-1.name": "رافعة شوكية FL-1",
  "fixture.docFolder.contracts": "العقود",
  "fixture.docFolder.rfis": "طلبات المعلومات",
  "fixture.docFolder.boqs": "جداول الكميات",
  "fixture.docFolder.drawings": "الرسومات",
  "fixture.docFolder.invoices": "الفواتير",
  "fixture.docFolder.safety": "أدلة السلامة",
  "fixture.doc.DOC-001.name": "العقد الرئيسي P-1042 — المراجعة C",
  "fixture.doc.DOC-002.name": "RFI-1042-013 التحميل الإنشائي",
  "fixture.doc.DOC-003.name": "جدول كميات P-1071 — القسم المدني",
  "fixture.doc.DOC-004.name": "A-1042-STR-042 — إطار رف الأنابيب",
  "fixture.doc.DOC-005.name": "حزمة فواتير المورد PO-1042-018",
  "fixture.doc.DOC-006.name": "دليل الصحة والسلامة والبيئة المؤسسي 2025",
  "fixture.doc.DOC-007.name": "مخطط موقع P-1058 — المراجعة B",
  "fixture.doc.DOC-008.name": "RFI-1071-006 واجهة الجدار الستائري",
  "fixture.activity.A-1.label": "أمر شراء بانتظار الاعتماد",
  "fixture.activity.A-2.label": "طلب معلومات متأخر",
  "fixture.activity.A-3.label": "صيانة معدات مستحقة",
  "fixture.activity.A-4.label": "إصدار رسم",
  "fixture.activity.A-5.label": "تحديث القوى العاملة",
  "fixture.deadline.D-1.label": "استحقاق الرد على RFI-1042-012",
  "fixture.deadline.D-2.label": "مراجعة خطة فحص أعمال التصريف P-1058",
  "fixture.deadline.D-3.label": "الإنجاز المخطط لـ P-1083",
  "fixture.deadline.D-4.label": "صيانة الرافعة البرجية TC-1",
} as const satisfies ContentDictionary;
