/**
 * Centralized English content layer (docs/06 §11, docs/19).
 * Arabic locale pack lives in ar.ts — keys are stable identifiers.
 */

export const en = {
  "common.brand.short": "FoundEarly",
  "common.brand.full": "FoundEarly Labs",
  "common.product": "Interactive Capability Showcase",
  "common.companyContext": "Al-Buraq Horizon Contracting",
  "common.action.close": "Close",
  "common.action.cancel": "Cancel",
  "common.action.confirm": "Confirm",
  "common.action.open": "Open",
  "common.loading": "Loading",
  "common.skipToContent": "Skip to main content",
  "common.search": "Search",
  "common.comingSoon": "Coming soon",
  "common.preview": "Preview",

  "nav.group.workspaces": "Workspaces",
  "nav.group.utility": "Utility",
  "nav.utility.about": "About this demo",
  "nav.workspaceSwitcher": "Switch workspace",
  "nav.sectionNav": "Workspace sections",
  "nav.projectSelector": "Active project",
  "nav.breadcrumb": "Breadcrumb",
  "nav.openCommand": "Open command palette",
  "nav.openSearch": "Open search",
  "nav.openNotifications": "Open notifications",

  "workspace.projectCommand.label": "Project Command",
  "workspace.projectCommand.description":
    "Portfolio health, project detail, and operational previews.",
  "workspace.projectCommand.section.overview": "Overview",
  "workspace.projectCommand.section.projectDetail": "Project Detail",
  "workspace.projectCommand.section.rfis": "RFIs",
  "workspace.projectCommand.section.documents": "Documents",
  "workspace.projectCommand.section.team": "Team",

  "workspace.corporateWebsite.label": "Corporate Website",
  "workspace.corporateWebsite.description":
    "Demo 01 — premium company website for Al-Buraq Horizon Contracting.",
  "workspace.corporateWebsite.section.home": "Home",
  "workspace.corporateWebsite.section.about": "About",
  "workspace.corporateWebsite.section.services": "Services",
  "workspace.corporateWebsite.section.projects": "Projects",
  "workspace.corporateWebsite.section.careers": "Careers",
  "workspace.corporateWebsite.section.contact": "Contact",

  "workspace.contractorOs.label": "ContractorOS",
  "workspace.contractorOs.description":
    "Demo 02 — contractor management platform for Al-Buraq Horizon Contracting.",
  "workspace.contractorOs.section.dashboard": "Dashboard",
  "workspace.contractorOs.section.projects": "Projects",
  "workspace.contractorOs.section.workforce": "Workforce",
  "workspace.contractorOs.section.equipment": "Equipment",
  "workspace.contractorOs.section.documents": "Documents",
  "workspace.contractorOs.section.purchaseOrders": "Purchase Orders",
  "workspace.contractorOs.section.settings": "Settings",

  "workspace.procurement.label": "Procurement & BOQ",
  "workspace.procurement.description": "Bill of quantities and procurement workflows.",
  "workspace.procurement.section.overview": "Overview",

  "workspace.documentControl.label": "Document Control",
  "workspace.documentControl.description": "Drawing and document register.",
  "workspace.documentControl.section.overview": "Overview",

  "workspace.rfiSubmittals.label": "RFI & Submittals",
  "workspace.rfiSubmittals.description": "RFI lifecycle and submittal register.",
  "workspace.rfiSubmittals.section.overview": "Overview",

  "shell.utilityRegion": "Utility region",
  "shell.rightUtility": "Contextual utilities",
  "shell.presentationToggle": "Presentation mode",
  "shell.presentationOn": "Presentation mode on",
  "shell.presentationOff": "Presentation mode off",
  "shell.themeSwitch": "Theme",
  "shell.theme.light": "Light",
  "shell.theme.dark": "Dark",
  "shell.theme.system": "System",
  "shell.languageSwitch": "Language",
  "shell.language.en": "English",
  "shell.language.ar": "Arabic",
  "shell.language.hint": "Switch interface language between English and Arabic.",

  "empty.workspace.title": "Workspace ready",
  "empty.workspace.description":
    "This section is registered in the workspace engine. Content surfaces arrive in a later phase.",
  "empty.search.title": "No matching results",
  "empty.search.description": "Try a different term, or clear the query to browse categories.",
  "empty.notifications.title": "No notifications",
  "empty.notifications.description":
    "System notices will appear here when the notification pipeline is connected.",
  "empty.presentation.title": "Presentation chrome is quiet",
  "empty.presentation.description":
    "Secondary chrome is dimmed so attention stays on the canvas. Press P to exit.",
  "empty.noData.title": "No data in this view",
  "empty.noData.description":
    "Fixture data for this surface has not been loaded yet. The shell remains fully navigable.",
  "empty.comingSoon.title": "Coming soon",
  "empty.comingSoon.description":
    "This workspace is reserved in the registry and will plug into the same shell when it ships.",

  "command.placeholder": "Search commands and destinations…",
  "command.empty": "No commands match that query.",
  "command.recent": "Recent",
  "command.quickActions": "Quick actions",
  "command.category.navigation": "Navigation",
  "command.category.presentation": "Presentation",
  "command.category.simulator": "Simulator",
  "command.category.workspace": "Workspace",
  "command.category.system": "System",
  "command.open": "Command palette",

  "search.placeholder": "Search the showcase…",
  "search.recent": "Recent searches",
  "search.categories": "Categories",
  "search.loading": "Searching…",
  "search.category.workspaces": "Workspaces",
  "search.category.sections": "Sections",
  "search.category.commands": "Commands",
  "search.category.projects": "Projects",
  "search.indexHint": "Placeholder index — no live search backend in Phase 1.",

  "notifications.title": "Notifications",
  "notifications.badge": "Unread notifications",
  "notifications.markAllRead": "Mark all read",
  "notifications.emptyAction": "Notification architecture is ready",

  "about.title": "About this demo",
  "about.description":
    "This Interactive Capability Showcase is built by FoundEarly Labs using illustrative data for Al-Buraq Horizon Contracting. It demonstrates platform architecture and interaction quality — not a live production system.",
  "about.shellReady": "Enterprise application shell and workspace engine are active.",

  "notFound.title": "Page not found",
  "notFound.description":
    "That link is not part of the current showcase. Return to the Project Command workspace.",
  "notFound.action": "Open Project Command",

  "landing.nav.solutions": "Solutions",
  "landing.nav.showcase": "Interactive Showcase",
  "landing.hero.brand": "FoundEarly Labs",
  "landing.hero.headline": "AI and software solutions built for construction companies.",
  "landing.hero.support":
    "We build custom websites, internal software, AI systems, and business automation for contractors and engineering firms who need tools that match how their projects actually run.",
  "landing.hero.ctaPrimary": "Explore Solutions",
  "landing.hero.ctaSecondary": "Interactive Showcase",

  "landing.trust.customSoftware": "Custom Software",
  "landing.trust.aiAutomation": "AI Automation",
  "landing.trust.dashboards": "Enterprise Dashboards",
  "landing.trust.workflows": "Construction Workflows",
  "landing.trust.businessAutomation": "Business Automation",
  "landing.trust.webPlatforms": "Web Platforms",

  "landing.about.title": "About FoundEarly Labs",
  "landing.about.body":
    "We partner with construction companies to modernize operations with custom software. Our work is shaped by how contractors, MEP firms, and engineering teams actually approve RFIs, control documents, and run projects — not by generic SaaS templates.",

  "landing.audience.title": "Who we help",
  "landing.audience.support": "Teams that need operational software as serious as the work they deliver.",
  "landing.audience.general": "General Contractors",
  "landing.audience.mep": "MEP Contractors",
  "landing.audience.civil": "Civil Contractors",
  "landing.audience.industrial": "Industrial Contractors",
  "landing.audience.engineering": "Engineering Consultants",
  "landing.audience.aramco": "Aramco Approved Companies",

  "landing.build.title": "What we build",
  "landing.build.support": "Practical systems for the office, the site, and the executive table.",
  "landing.build.websites.title": "Corporate Websites",
  "landing.build.websites.body": "Credible web presence that reflects how your company actually wins work.",
  "landing.build.websites.cta": "Open Demo 01",
  "landing.build.contractor.title": "Contractor Management Systems",
  "landing.build.contractor.body": "Internal platforms for projects, teams, vendors, and day-to-day control.",
  "landing.build.contractor.cta": "Open Demo 02",
  "landing.build.ai.title": "AI Assistants",
  "landing.build.ai.body": "Scoped assistants grounded in your documents, logs, and operating context.",
  "landing.build.dashboards.title": "Executive Dashboards",
  "landing.build.dashboards.body": "Schedule, budget, and risk visibility designed for decision-makers.",
  "landing.build.mobile.title": "Mobile Applications",
  "landing.build.mobile.body": "Field-ready apps for inspections, updates, and site coordination.",
  "landing.build.automation.title": "Business Automation",
  "landing.build.automation.body": "Replace spreadsheet handoffs with reliable, repeatable workflows.",
  "landing.build.documents.title": "Document Management",
  "landing.build.documents.body": "Controlled registers for drawings, submittals, and version history.",

  "landing.why.title": "Why FoundEarly",
  "landing.why.support": "Built as an engineering partner, not a packaged product pitch.",
  "landing.why.traditional": "Traditional software",
  "landing.why.foundearly": "FoundEarly Labs",
  "landing.why.item1.traditional": "Forces your process into the product",
  "landing.why.item1.ours": "Built around your workflow",
  "landing.why.item2.traditional": "Rigid modules and slow change cycles",
  "landing.why.item2.ours": "Scalable custom development",
  "landing.why.item3.traditional": "Dense, dated interfaces",
  "landing.why.item3.ours": "Modern, precise UI",
  "landing.why.item4.traditional": "AI bolted on later",
  "landing.why.item4.ours": "AI-ready from the start",
  "landing.why.item5.traditional": "Long delivery timelines",
  "landing.why.item5.ours": "Fast, focused delivery",

  "landing.cta.title": "Let's build software around your business.",
  "landing.cta.support": "Open the Interactive Capability Showcase to see how we design enterprise construction software.",
  "landing.cta.action": "Open Interactive Showcase",

  "website.nav.label": "Company website",
  "website.nav.home": "Home",
  "website.nav.about": "About",
  "website.nav.services": "Services",
  "website.nav.projects": "Projects",
  "website.nav.careers": "Careers",
  "website.nav.contact": "Contact",
  "website.nav.contactCta": "Contact",
  "website.nav.open": "Open menu",
  "website.nav.close": "Close menu",

  "website.footer.offices": "Head office",
  "website.footer.contact": "Contact",
  "website.footer.demoNote": "Illustrative Demo 01 — FoundEarly Labs Showcase",

  "website.home.hero.title": "Construction delivery for industrial and civil clients.",
  "website.home.hero.support":
    "Al-Buraq Horizon Contracting plans and executes complex packages across the Eastern Province and Riyadh — with the discipline industrial owners expect.",
  "website.home.hero.ctaPrimary": "View projects",
  "website.home.hero.ctaSecondary": "Request a meeting",

  "website.home.intro.title": "Company introduction",
  "website.home.intro.body":
    "Founded in 2009 and headquartered in Al-Khobar, Al-Buraq Horizon is a Grade 2 general contractor with MEP self-execution capability. We serve industrial, commercial, and infrastructure clients who need clear reporting, controlled interfaces, and site teams that treat safety as a delivery system.",

  "website.home.services.title": "Core services",
  "website.home.services.support": "Disciplined packages from enabling works through MEP and handover.",
  "website.home.services.cta": "All services",

  "website.home.projects.title": "Featured projects",
  "website.home.projects.support": "A sample of active and completed work across our portfolio.",

  "website.home.why.title": "Why choose us",
  "website.home.why.support": "What clients evaluate when they select a contractor for industrial work.",

  "website.home.clients.title": "Selected clients",

  "website.home.cta.title": "Discuss your next package.",
  "website.home.cta.support":
    "Speak with our Al-Khobar team about scope, schedule, and delivery approach for your project.",
  "website.home.cta.action": "Contact Al-Buraq Horizon",

  "website.about.eyebrow": "About",
  "website.about.title": "Built for industrial-grade delivery.",
  "website.about.support":
    "Seventeen years of contracting discipline across civil, industrial, and MEP packages in Saudi Arabia.",

  "website.about.story.title": "Company story",
  "website.about.story.p1":
    "Al-Buraq Horizon Contracting Co. was established in 2009 in Al-Khobar to serve industrial and commercial clients who needed a contractor that could coordinate civil and MEP work without losing schedule control.",
  "website.about.story.p2":
    "Today we employ approximately 940 professionals and operate across Al-Khobar, Dammam, Jubail, Dhahran, Riyadh, and Yanbu — delivering facilities, utilities, and enabling works under Grade 2 and Aramco-aligned requirements.",

  "website.about.mission.title": "Mission",
  "website.about.mission.body":
    "Deliver construction packages with predictable schedule, transparent commercial control, and zero compromise on site safety.",

  "website.about.vision.title": "Vision",
  "website.about.vision.body":
    "Be the preferred mid-market industrial contractor in the Eastern Province — measured by repeat clients, clean audits, and teams that grow with every project.",

  "website.about.leadership.title": "Leadership",
  "website.about.leadership.support":
    "A core leadership team reused across the portfolio — the same names clients meet on every major package.",

  "website.about.safety.title": "Safety commitment",
  "website.about.safety.body":
    "Every site operates under permit-to-work discipline, daily toolbox talks, and stop-work authority for any unsafe condition. Safety KPIs are reported with the same seriousness as schedule and cost.",

  "website.about.quality.title": "Quality commitment",
  "website.about.quality.body":
    "Inspection and test plans, MIR/WIR workflows, and NCR close-out are controlled through project quality registers. We do not treat quality as paperwork after the fact.",

  "website.about.certs.title": "Certifications",

  "website.services.eyebrow": "Services",
  "website.services.title": "Capabilities matched to how packages are actually tendered.",
  "website.services.support":
    "Civil, industrial, MEP, infrastructure, maintenance, and project management — structured for clear interfaces.",

  "website.projects.eyebrow": "Projects",
  "website.projects.title": "Portfolio across industrial, commercial, and enabling works.",
  "website.projects.support":
    "Six representative packages from the Al-Buraq Horizon portfolio. Values shown in Saudi Riyal.",
  "website.projects.meta.location": "Location",
  "website.projects.meta.value": "Value",
  "website.projects.meta.year": "Completion year",
  "website.projects.meta.scope": "Scope type",

  "website.careers.eyebrow": "Careers",
  "website.careers.title": "Build with a team that takes delivery seriously.",
  "website.careers.support":
    "Open roles across projects, engineering, quality, and document control.",

  "website.careers.culture.title": "Company culture",
  "website.careers.culture.body":
    "We hire people who communicate clearly, respect site protocols, and treat documentation as part of the work — not an afterthought. Teams rotate between office planning and site execution with accountable supervisors.",

  "website.careers.benefits.title": "Benefits",
  "website.careers.open.title": "Open positions",
  "website.careers.open.support": "Current openings. Applications are illustrative in this demo.",

  "website.careers.apply.title": "Apply",
  "website.careers.apply.support":
    "Send your CV and a short note on relevant project experience to our careers inbox, or use the contact form.",
  "website.careers.apply.cta": "Contact careers",

  "website.contact.eyebrow": "Contact",
  "website.contact.title": "Speak with our head office team.",
  "website.contact.support":
    "Project inquiries, vendor introductions, and careers — directed from Al-Khobar.",

  "website.contact.office.title": "Office",
  "website.contact.details.title": "Direct lines",
  "website.contact.phone": "Phone",
  "website.contact.email": "Email",
  "website.contact.map.title": "Map placeholder",
  "website.contact.map.support":
    "Al-Khobar head office location. Live map embedding is not required for this showcase.",

  "website.contact.form.title": "Send a message",
  "website.contact.form.support": "UI-only form — no backend submission in this demo.",
  "website.contact.form.name": "Full name",
  "website.contact.form.email": "Work email",
  "website.contact.form.company": "Company",
  "website.contact.form.message": "Message",
  "website.contact.form.submit": "Send message",
  "website.contact.form.note": "Illustrative only — nothing is transmitted.",
  "website.contact.form.success": "Message recorded locally for this demo session.",

  "os.dashboard.eyebrow": "ContractorOS",
  "os.dashboard.title": "Executive dashboard",
  "os.dashboard.support":
    "Portfolio health for Al-Buraq Horizon Contracting — schedule, workforce, equipment, and commercial control.",
  "os.dashboard.projectStatus": "Project status",
  "os.dashboard.viewProjects": "View projects",
  "os.dashboard.activity": "Recent activity",
  "os.dashboard.deadlines": "Upcoming deadlines",
  "os.dashboard.quickActions": "Quick actions",

  "os.kpi.activeProjects": "Active projects",
  "os.kpi.activeProjects.hint": "Excludes completed packages",
  "os.kpi.employeesOnSite": "Employees on site",
  "os.kpi.employeesOnSite.hint": "Across Eastern Province and Riyadh",
  "os.kpi.equipmentUtilization": "Equipment utilization",
  "os.kpi.equipmentUtilization.hint": "Assigned assets vs fleet",
  "os.kpi.openPos": "Open purchase orders",
  "os.kpi.openPos.hint": "Not yet delivered",
  "os.kpi.pendingApprovals": "Pending approvals",
  "os.kpi.pendingApprovals.hint": "POs awaiting director sign-off",
  "os.kpi.monthlyRevenue": "Monthly revenue",
  "os.kpi.monthlyRevenue.hint": "Recognized progress this month",

  "os.action.projects": "Open projects",
  "os.action.workforce": "Workforce roster",
  "os.action.equipment": "Equipment fleet",
  "os.action.documents": "Document browser",
  "os.action.pos": "Purchase orders",
  "os.action.reviewApprovals": "Review approvals",

  "os.projects.title": "Projects",
  "os.projects.support": "Six packages in the Al-Buraq Horizon portfolio. Select a row for a clean overview.",
  "os.projects.search": "Search projects…",
  "os.projects.back": "Back to projects",
  "os.projects.meta.location": "Location",
  "os.projects.meta.value": "Project value",
  "os.projects.meta.manager": "Project manager",
  "os.projects.meta.client": "Client",
  "os.projects.meta.type": "Type",
  "os.projects.meta.completion": "Completion date",

  "os.workforce.title": "Workforce",
  "os.workforce.support": "Core roster on active sites. Initials avatars — no fictional headshots.",
  "os.workforce.search": "Search employees…",
  "os.workforce.col.employee": "Employee",
  "os.workforce.col.role": "Role",
  "os.workforce.col.site": "Site",
  "os.workforce.col.status": "Status",
  "os.workforce.col.shift": "Shift",
  "os.workforce.col.project": "Project",

  "os.equipment.title": "Equipment",
  "os.equipment.support": "Owned and yard-held plant assigned across the portfolio.",
  "os.equipment.search": "Search equipment…",
  "os.equipment.col.asset": "Asset",
  "os.equipment.col.type": "Type",
  "os.equipment.col.status": "Status",
  "os.equipment.col.location": "Location",
  "os.equipment.col.project": "Assigned project",
  "os.equipment.col.maintenance": "Next maintenance",

  "os.documents.title": "Documents",
  "os.documents.support": "Controlled folders for contracts, RFIs, BOQs, drawings, invoices, and safety manuals.",
  "os.documents.search": "Search documents…",
  "os.documents.folder": "Category",
  "os.documents.folders": "Folders",
  "os.documents.recent": "Documents",
  "os.documents.preview": "Preview",
  "os.documents.previewHint": "Document preview placeholder — illustrative only.",
  "os.documents.none": "No document selected.",
  "os.documents.meta.id": "Document ID",
  "os.documents.meta.owner": "Owner",
  "os.documents.meta.project": "Project",
  "os.documents.meta.status": "Status",

  "os.pos.title": "Purchase orders",
  "os.pos.support": "Read-only PO register for Al-Buraq Horizon vendors. No editing in this demo.",
  "os.pos.search": "Search purchase orders…",
  "os.pos.col.number": "PO number",
  "os.pos.col.vendor": "Vendor",
  "os.pos.col.amount": "Amount",
  "os.pos.col.status": "Status",
  "os.pos.col.approval": "Approval",
  "os.pos.col.project": "Project",

  "os.settings.title": "Settings",
  "os.settings.support": "Company preferences for the ContractorOS showcase. Pure UI — nothing is persisted.",
  "os.settings.nav": "Settings sections",
  "os.settings.nav.branding": "Branding",
  "os.settings.nav.notifications": "Notifications",
  "os.settings.nav.language": "Language",
  "os.settings.nav.theme": "Theme",
  "os.settings.nav.roles": "Roles",
  "os.settings.nav.permissions": "Permissions",
  "os.settings.branding.support": "Wordmark and company identity shown across the platform.",
  "os.settings.branding.company": "Legal name",
  "os.settings.branding.short": "Short name",
  "os.settings.branding.mark": "Mark",
  "os.settings.branding.accent": "Accent token",
  "os.settings.notifications.support": "Illustrative notification preferences for live operations.",
  "os.settings.notifications.approvals": "PO approval alerts",
  "os.settings.notifications.rfis": "RFI SLA alerts",
  "os.settings.notifications.maintenance": "Equipment maintenance reminders",
  "os.settings.notifications.weekly": "Weekly portfolio digest",
  "os.settings.language.support": "UI language and date formatting for the showcase.",
  "os.settings.language.ui": "Interface language",
  "os.settings.language.dates": "Date format",
  "os.settings.theme.support": "Appearance preferences for presentation and day-to-day use.",
  "os.settings.theme.mode": "Color mode",
  "os.settings.theme.density": "Density",
  "os.settings.roles.support": "Role definitions mirrored from Al-Buraq Horizon delivery structure.",
  "os.settings.roles.illustrative": "Illustrative",
  "os.settings.permissions.support": "Capability toggles for showcase roles — not enforced.",
  "os.settings.permissions.export": "Export registers",
  "os.settings.permissions.approvePo": "Approve purchase orders",
  "os.settings.permissions.editDocs": "Edit controlled documents",
  "os.settings.permissions.manageUsers": "Manage user accounts",
  "os.settings.save": "Save settings",
  "os.settings.reset": "Discard",
  "os.settings.saved": "Settings recorded locally for this demo session.",
  "os.settings.note": "UI only — no backend persistence.",

  "os.filter.status": "Status",
  "os.filter.all": "All",
  "os.empty.filtered": "No records match these filters. Clear search or status.",

  "shell.language.badge.en": "EN",
  "shell.language.badge.ar": "ع",
  "common.progress": "Progress",
  "error.boundary.title": "Something interrupted this view",
  "error.boundary.description":
    "The showcase recovered safely. Retry this surface, or continue from the shell navigation.",
  "error.boundary.retry": "Try again",
  "overlay.close": "Close overlay",
  "landing.nav.aria": "Landing",
  "landing.capabilities.aria": "Capabilities",
  "command.setActiveProject": "Set active project {code}",
  "search.project.defaultDescription": "Default active project after Demo Reset",
  "shortcut.presentation": "Toggle Presentation Mode",
  "shortcut.fullscreen": "Toggle Fullscreen",
  "status.onTrack": "On Track",
  "status.atRisk": "At Risk",
  "status.delayed": "Delayed",
  "status.complete": "Complete",
  "status.draft": "Draft",
  "status.pendingApproval": "Pending Approval",
  "status.approved": "Approved",
  "status.issuedToVendor": "Issued to Vendor",
  "status.delivered": "Delivered",
  "status.onHold": "On Hold",
  "status.current": "Current",
  "status.superseded": "Superseded",
  "status.underRevision": "Under Revision",
  "status.onSite": "On Site",
  "status.offShift": "Off Shift",
  "status.leave": "Leave",
  "status.assigned": "Assigned",
  "status.available": "Available",
  "status.maintenance": "Maintenance",
  "status.day": "Day",
  "status.night": "Night",
  "status.office": "Office",
  "status.fullTime": "Full-time",
  "status.contract": "Contract",
  "status.watch": "Watch",
  "status.overdue": "Overdue",
  "status.open": "Open",
  "os.settings.language.option.en": "English",
  "os.settings.language.option.ar": "Arabic",
  "os.settings.language.dateFormat": "DD MMM YYYY",
  "os.settings.theme.option.system": "System",
  "os.settings.theme.option.light": "Light",
  "os.settings.theme.option.dark": "Dark",
  "os.settings.theme.option.comfortable": "Comfortable",
  "os.settings.theme.option.compact": "Compact",
  "os.settings.branding.accentValue": "Brand primary",
  "os.settings.roles.projectDirector": "Project Director",
  "os.settings.roles.projectDirector.access": "Full portfolio",
  "os.settings.roles.projectManager": "Project Manager",
  "os.settings.roles.projectManager.access": "Assigned projects",
  "os.settings.roles.procurementLead": "Procurement Lead",
  "os.settings.roles.procurementLead.access": "POs and vendors",
  "os.settings.roles.documentController": "Document Controller",
  "os.settings.roles.documentController.access": "Registers and drawings",
  "website.company.tagline": "Industrial and civil construction across the Kingdom.",
  "website.company.industry": "General Contractor",
  "website.company.headquarters": "Al-Khobar, Eastern Province, Saudi Arabia",
  "website.company.classification": "Grade 2 Contractor — Saudi Contractors Authority",
  "website.company.stat.years": "Years in business",
  "website.company.stat.projects": "Projects delivered",
  "website.company.stat.professionals": "Professionals",
  "website.company.stat.cities": "Cities served",
  "website.company.cert.iso9001": "ISO 9001:2015 Quality Management",
  "website.company.cert.iso45001": "ISO 45001:2018 Occupational Health & Safety",
  "website.company.cert.iso14001": "ISO 14001:2015 Environmental Management",
  "website.company.cert.aramco": "Aramco Approved Vendor (AR-CL-2291)",
  "website.company.cert.grade2": "Saudi Contractors Authority — Grade 2",
  "website.company.city.khobar": "Al-Khobar",
  "website.company.city.dammam": "Dammam",
  "website.company.city.jubail": "Jubail Industrial City",
  "website.company.city.dhahran": "Dhahran",
  "website.company.city.riyadh": "Riyadh",
  "website.company.city.yanbu": "Yanbu",
  "website.company.address.street": "Prince Faisal Bin Fahd Road",
  "website.company.address.city": "Al-Khobar 34427",
  "website.company.address.country": "Kingdom of Saudi Arabia",
  "website.service.civil.title": "Civil Construction",
  "website.service.civil.summary":
    "Structural concrete, earthworks, and building envelopes for industrial and commercial facilities.",
  "website.service.industrial.title": "Industrial Projects",
  "website.service.industrial.summary":
    "Process support facilities, utility upgrades, and plant infrastructure for petrochemical and manufacturing sites.",
  "website.service.mep.title": "MEP",
  "website.service.mep.summary":
    "Mechanical, electrical, and plumbing packages executed with in-house supervision and qualified subcontractors.",
  "website.service.infrastructure.title": "Infrastructure",
  "website.service.infrastructure.summary":
    "Roads, utilities, enabling works, and site development for logistics and mixed-use developments.",
  "website.service.maintenance.title": "Maintenance",
  "website.service.maintenance.summary":
    "Planned shutdown support, corrective works, and facilities maintenance under controlled method statements.",
  "website.service.pm.title": "Project Management",
  "website.service.pm.summary":
    "Schedule control, cost reporting, document control, and client interface across multi-discipline packages.",
  "website.why.delivery.title": "Delivery discipline",
  "website.why.delivery.body":
    "Schedule, cost, and document control are treated as core project systems — not afterthoughts.",
  "website.why.industrial.title": "Industrial credibility",
  "website.why.industrial.body":
    "Aramco-aligned processes and Grade 2 classification for clients who require proven vendor capability.",
  "website.why.mep.title": "Self-performed MEP strength",
  "website.why.mep.body":
    "MEP packages are planned and supervised in-house, reducing interface risk on complex facilities.",
  "website.why.safety.title": "Safety before schedule",
  "website.why.safety.body":
    "PTW discipline, toolbox talks, and stop-work authority are non-negotiable on every site.",
  "website.benefit.1": "Competitive salary and annual performance review",
  "website.benefit.2": "Medical coverage for employees and eligible dependents",
  "website.benefit.3": "Structured career paths across projects and disciplines",
  "website.benefit.4": "Site and office rotation with clear HSE standards",
  "website.benefit.5": "Training support for technical and professional certifications",
  "fixture.type.industrial": "Industrial",
  "fixture.type.industrialCivil": "Industrial / Civil",
  "fixture.type.commercialMep": "Commercial / MEP",
  "fixture.type.industrialMep": "Industrial / MEP",
  "fixture.type.civil": "Civil",
  "fixture.location.jubail": "Jubail Industrial City",
  "fixture.location.dhahran": "Dhahran",
  "fixture.location.riyadh": "Riyadh",
  "fixture.location.yanbu": "Yanbu",
  "fixture.location.khobar": "Al-Khobar",
  "fixture.location.dammam": "Dammam",
  "fixture.location.khobarHq": "Al-Khobar (HQ)",
  "fixture.location.khobarYard": "Al-Khobar Yard",
  "fixture.location.jubailShort": "Jubail",
  "fixture.project.P-1042.name": "Jubail Process Utility Upgrade",
  "fixture.project.P-1042.scope":
    "Utility corridor, piping racks, and civil packages for process support infrastructure.",
  "fixture.project.P-1042.summary":
    "Utility corridor, piping racks, and civil packages for process support infrastructure.",
  "fixture.project.P-1058.name": "Dhahran Logistics Hub Expansion",
  "fixture.project.P-1058.scope":
    "Warehouse expansion, yard paving, and stormwater infrastructure for a regional logistics operator.",
  "fixture.project.P-1058.summary": "Warehouse expansion, yard paving, and stormwater infrastructure.",
  "fixture.project.P-1071.name": "Riyadh Corporate Campus — Phase 2",
  "fixture.project.P-1071.scope":
    "Commercial structure, façade, and MEP fit-out for a multi-building corporate campus.",
  "fixture.project.P-1071.summary": "Commercial structure, façade, and MEP fit-out for a multi-building campus.",
  "fixture.project.P-1083.name": "Yanbu Desalination Support Facility",
  "fixture.project.P-1083.scope":
    "MEP-led support buildings, electrical rooms, and ancillary civil works for a desalination campus.",
  "fixture.project.P-1083.summary": "MEP-led support buildings, electrical rooms, and ancillary civil works.",
  "fixture.project.P-1096.name": "Al-Khobar Waterfront Mixed-Use — Enabling Works",
  "fixture.project.P-1096.nameShort": "Al-Khobar Waterfront — Enabling Works",
  "fixture.project.P-1096.scope":
    "Site enabling, retaining structures, and utilities for a coastal mixed-use development.",
  "fixture.project.P-1096.summary": "Site enabling, retaining structures, and utilities for coastal mixed-use.",
  "fixture.project.P-1102.name": "Jubail Industrial Warehouse Complex",
  "fixture.project.P-1102.scope":
    "Four warehouse bays, office block, and external works for an industrial estates operator.",
  "fixture.project.P-1102.summary": "Four warehouse bays, office block, and external works.",
  "fixture.leader.faisal.role": "Project Director",
  "fixture.leader.faisal.focus":
    "Portfolio delivery and client governance across Eastern Province industrial packages.",
  "fixture.leader.noura.role": "Senior Project Manager",
  "fixture.leader.noura.focus":
    "Schedule and commercial control for multi-discipline industrial and civil projects.",
  "fixture.leader.lina.role": "QA/QC Manager",
  "fixture.leader.lina.focus": "Inspection regimes, NCR close-out, and ISO-aligned quality systems.",
  "fixture.leader.khalid.role": "Procurement Lead",
  "fixture.leader.khalid.focus": "Vendor qualification, long-lead materials, and Aramco-aligned supply chains.",
  "fixture.role.pmRiyadh.title": "Project Manager — Commercial",
  "fixture.role.pmRiyadh.department": "Projects",
  "fixture.role.pmRiyadh.summary":
    "Lead delivery for campus and commercial packages, including client reporting and variation control.",
  "fixture.role.peJubail.title": "Project Engineer — Civil",
  "fixture.role.peJubail.department": "Engineering",
  "fixture.role.peJubail.summary":
    "Support site execution, RFIs, and method statements on industrial civil packages.",
  "fixture.role.qaDammam.title": "QA/QC Engineer",
  "fixture.role.qaDammam.department": "Quality",
  "fixture.role.qaDammam.summary":
    "Plan inspections, manage MIR/WIR workflows, and maintain the project quality register.",
  "fixture.role.dcKhobar.title": "Document Controller",
  "fixture.role.dcKhobar.department": "Document Control",
  "fixture.role.dcKhobar.summary": "Maintain drawing and submittal registers with disciplined revision control.",
  "fixture.job.projectDirector": "Project Director",
  "fixture.job.seniorProjectManager": "Senior Project Manager",
  "fixture.job.projectManager": "Project Manager",
  "fixture.job.projectEngineerCivil": "Project Engineer (Civil)",
  "fixture.job.projectEngineerMep": "Project Engineer (MEP)",
  "fixture.job.qaqcManager": "QA/QC Manager",
  "fixture.job.procurementLead": "Procurement Lead",
  "fixture.job.documentController": "Document Controller",
  "fixture.job.siteEngineer": "Site Engineer",
  "fixture.job.costController": "Cost Controller",
  "fixture.equipment.type.excavator": "Excavator",
  "fixture.equipment.type.crane": "Crane",
  "fixture.equipment.type.concretePump": "Concrete Pump",
  "fixture.equipment.type.generator": "Generator",
  "fixture.equipment.type.forklift": "Forklift",
  "fixture.equipment.EX-1.name": "Excavator EX-1",
  "fixture.equipment.EX-2.name": "Excavator EX-2",
  "fixture.equipment.TC-1.name": "Tower Crane TC-1",
  "fixture.equipment.MC-1.name": "Mobile Crane MC-1 (50T)",
  "fixture.equipment.CP-1.name": "Concrete Pump CP-1",
  "fixture.equipment.GS-1.name": "Generator Set GS-1 (500kVA)",
  "fixture.equipment.GS-2.name": "Generator Set GS-2 (500kVA)",
  "fixture.equipment.FL-1.name": "Forklift FL-1",
  "fixture.docFolder.contracts": "Contracts",
  "fixture.docFolder.rfis": "RFIs",
  "fixture.docFolder.boqs": "BOQs",
  "fixture.docFolder.drawings": "Drawings",
  "fixture.docFolder.invoices": "Invoices",
  "fixture.docFolder.safety": "Safety Manuals",
  "fixture.doc.DOC-001.name": "P-1042 Main Contract — Rev C",
  "fixture.doc.DOC-002.name": "RFI-1042-013 Structural Loading",
  "fixture.doc.DOC-003.name": "P-1071 BOQ — Civil Section",
  "fixture.doc.DOC-004.name": "A-1042-STR-042 — Pipe Rack Framing",
  "fixture.doc.DOC-005.name": "PO-1042-018 Supplier Invoice Pack",
  "fixture.doc.DOC-006.name": "Corporate HSE Manual 2025",
  "fixture.doc.DOC-007.name": "P-1058 Site Layout — Rev B",
  "fixture.doc.DOC-008.name": "RFI-1071-006 Curtain Wall Interface",
  "fixture.activity.A-1.label": "PO pending approval",
  "fixture.activity.A-2.label": "RFI overdue",
  "fixture.activity.A-3.label": "Equipment maintenance due",
  "fixture.activity.A-4.label": "Drawing issued",
  "fixture.activity.A-5.label": "Workforce update",
  "fixture.deadline.D-1.label": "RFI-1042-012 response due",
  "fixture.deadline.D-2.label": "P-1058 stormwater ITP review",
  "fixture.deadline.D-3.label": "P-1083 planned finish",
  "fixture.deadline.D-4.label": "TC-1 tower crane maintenance",
} as const;

export type ContentKey = keyof typeof en;

export type ContentDictionary = Record<ContentKey, string>;
